version: "2.14.1"

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgresdb
      - POSTGRES_DB=autorenter_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: autorenter
    ports:
      - 3333:3333
    volumes:
      - .:/usr/autorenter-api
    network_mode: host

volumes:
  pgdata:
    driver: local